name: CI

permissions: {}

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  test-go:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # required for git am --3way to work properly
          submodules: true
          persist-credentials: false

      - uses: oxc-project/setup-node@ab97f03642370d79a7e96dd286bd02a1be40e0ba # v1.3.0

      - uses: ./.github/actions/setup

      - name: Run go tests
        run: go test ./internal/...

  test-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # required for git am --3way to work properly
          submodules: true
          persist-credentials: false

      - uses: oxc-project/setup-node@ab97f03642370d79a7e96dd286bd02a1be40e0ba # v1.3.0

      - uses: ./.github/actions/setup

      - name: Build
        run: just build

      - name: Run e2e tests
        run: |
          pnpm --ignore-workspace install --frozen-lockfile
          pnpm --ignore-workspace run test
        working-directory: e2e

  test-windows:
    if: ${{ github.ref_name == 'main' }}
    runs-on: windows-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # required for git am --3way to work properly
          submodules: true
          persist-credentials: false

      - uses: oxc-project/setup-node@ab97f03642370d79a7e96dd286bd02a1be40e0ba # v1.3.0

      - uses: ./.github/actions/setup

      - name: Build
        run: go build -o tsgolint.exe ./cmd/tsgolint

      - name: Run e2e tests
        run: |
          pnpm --ignore-workspace install --frozen-lockfile
          pnpm --ignore-workspace run test
        working-directory: e2e

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # required for git am --3way to work properly
          submodules: true
          persist-credentials: false

      - uses: ./.github/actions/setup

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: latest

  typos:
    name: Typos
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: crate-ci/typos@f8a58b6b53f2279f71eb605f03a4ae4d10608f45 # v1.47.0
        with:
          files: .
