name: Save dprint plugin cache

permissions: {}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "dprint.json"
      - ".github/workflows/dprint.yml"

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1

      - uses: taiki-e/install-action@06203676c62f0d3c765be3f2fcfbebbcb02d09f5 # v2.69.6
        with:
          tool: dprint

      - run: dprint check

      - name: Save dprint plugin cache
        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          key: dprint-${{ hashFiles('dprint.json') }}
          path: ~/.cache/dprint
