name: Save dprint plugin cache

permissions: {}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "dprint.json"
      - ".github/workflows/dprint.yml"

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: taiki-e/install-action@15413b256f995d819248ea62704771a959284285 # v2.79.13
        with:
          tool: dprint

      - run: dprint check

      - name: Save dprint plugin cache
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          key: dprint-${{ hashFiles('dprint.json') }}
          path: ~/.cache/dprint
